-----------Assignment 2------------------
select * from salesman
select * from orders
select * from customer

--1.write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id--------------
	select ord_no,ord_date,customer_id,orders.salesman_id from orders,salesman where salesman.salesman_id=orders.salesman_id and salesman.name='Paul Adam'

--2.write a SQL query to find all the orders, which are generated by those salespeople, who live in the city of London.Return ord_no, purch_amt, ord_date, customer_id, salesman_id.---------
	select ord_no,ord_date,customer_id,orders.salesman_id from orders,salesman where salesman.salesman_id=orders.salesman_id and salesman.city='London'

--3.write a SQL query to find the orders generated by the salespeople who works for customers whose id is 3007. Return ord_no, purch_amt, ord_date, customer_id, salesman_id. A customer can works only with a salespeople-----------
	select ord_no,ord_date,customer_id,orders.salesman_id from orders where orders.customer_id in(select customer_id from orders where orders.customer_id=3007)

--4.write a SQL query to find the order values greater than the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.------------
	select ord_no,ord_date,customer_id,orders.salesman_id from orders where purch_amt > (select avg(purch_amt) from orders where ord_date='2012-10-10')

--5.write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id---------------
	select ord_no,purch_amt,ord_date,customer_id,orders.salesman_id from orders where salesman_id in (select salesman_id from salesman where city='New York')

--6.write a SQL query to find the salespeople who had more than one customer. Return salesman_id and name-----------------
	select salesman_id,name from salesman a where 1 <(select count(*) from customer where salesman_id=a.salesman_id)

--7.write a SQL query to find those orders, which are higher than average amount of the orders. Return ord_no, purch_amt, ord_date, customer_id and salesman_id---------
	select ord_no,ord_date,customer_id,orders.salesman_id from orders where purch_amt > (select avg(purch_amt) from orders )

--8.Write a query to find the sums of the amounts from the orders table, grouped by date, eliminating all those dates where the sum was not at least 1000.00 above the maximum order amount for that date---------
	SELECT ord_date, SUM (purch_amt)FROM orders a
	GROUP BY ord_date
	HAVING SUM (purch_amt) >
    (SELECT 1000.00 + MAX(purch_amt) 
     FROM orders b 
     WHERE a.ord_date = b.ord_date);

--9. Write a query to extract all data from the customer table if and only if one or more of the customers in the customer table are located in London.---------
	select customer_id,cust_name,city from customer where exists (select * from customer where city='London')

--10.write a SQL query to find the salespeople who deal multiple customers. Return salesman_id, name, city and commission------------
	SELECT * 
	FROM salesman 
	WHERE salesman_id IN (
	SELECT DISTINCT salesman_id 
	FROM customer a 
	WHERE NOT EXISTS (
      SELECT * FROM customer b 
      WHERE a.salesman_id=b.salesman_id 
      AND a.cust_name<>b.cust_name));